### ISSUE TITLE
prettier-plugin-toml removes blank lines after comments

### ISSUE THREAD

**Issue by EvgenyOrekhov** [un-ts/toml-tools#74]
Example:

```toml
# This is a TOML comment

# This is a multiline
# TOML comment

str1 = "I'm a string."
```

Expected: code should not be changed.

Actual:

```toml
# This is a TOML comment
# This is a multiline
# TOML comment
str1 = "I'm a string."
```

**Comment by JounQin** [comment]
Why not

**Comment by EvgenyOrekhov** [comment]
Comment that immediately precedes a line of code is meant for that specific line of code. Comment that has a blank line is either a global comment, or a comment for a section in the file.

```toml
# This is a global comment for the file
# blah blah

# This is a comment specifically for the next line
foo = "bar"

# This is a comment for the next section

bar = "baz"
baz = "qux"

# Another section

...
```
